Add sort command for LocalCourse
AY2324S1-CS2103T-W10-2/tp pull request #115
Opened 2023-10-24 17:46 UTC by dlathyun

Add LocalCourse sort command and edit related classes
Add LocalCourse sort command related tests

2023-10-26 08:11 UTC, alyssaongyx reviewed
LGTM!

2023-10-26 11:42 UTC, lamchenghou requested changes
Hey @dlathyun, as discussed earlier, hope you can help make a few changes:
- We want to set the primary key (unique identifier) of `PartnerCourse` to {`PartnerCode`, `UniversityName`}. The first step can be to modify `isSamePartnerCourse`. 
- With this, ensure that we can add partner courses with either matching `PartnerCode` or matching `UniversityName` (exclusive or). 
- Ensure that duplicate catching matches as well, no two distinct partner courses have both the same `PartnerCode` and `UniversityName`.

2023-10-26 11:42 UTC, lamchenghou commented on src/main/java/seedu/address/logic/commands/LocalCourseSortCommand.java
> +        return comparator.toString().equals(otherLocalCourseSortCommand.comparator.toString());
Is this the correct way to compare equality of comparators?

2023-10-27 05:09 UTC, lamchenghou approved these changes

2023-10-27 05:11 UTC, merged